### PR TITLE
Line height fix

### PR DESCRIPTION
**Pull request by bap14**
Messages containing numerous emotes (spam) could potentially wrap onto a second line causing an overlap of the emote over the text.  This adjusts the line-height for only those messages containing an emote.

### CODE REVIEW

**Comment by mccxiv** [comment]
Thanks, I took a quick look and I'll have some feedback before we merge. Will write after work

**Comment by mccxiv** [comment]
Your code actually got me thinking, because I was trying to see if we could do it without iterating the whole list on every new message. I think we can achieve this effect without any Javascript at all.

Here's how it's looking on my end with just some CSS changes (BTTV for comparison):

**Comment by bap14** [comment]
I initially thought about doing that; however, it caused the spacing of the text to look a bit too spaced out. Did you just adjust `.chat-line` class to have a line-height of 28 or 30px?  How does it look if someone types a really long regular message?  This is the issue I ran into.  Making all messages the same height would cause longer messages (like this paragraph of text) to be spaced out and look really spaced out instead of closer together like it does now.  I was trying to not make a huge shift in the UI for messages, while supporting emotes to not overlap either text or other emotes.

I could adjust the code so that as a new message is parsed for an emote it adds the `_containsEmote` property to the message object.  I think I can do that, iirc.  Matter of fact, I'm not sure why I didn't do that in the first place.

**Comment by mccxiv** [comment]
I removed the explicit `line-height` completely, this causes messages with emotes to be naturally taller. the issue I'm having right now is that back-to-back messages with emotes look a bit too spaced out. I think it's that 4px padding we have on each line. But removing that padding makes non emote lines look too cramped.

I would much prefer a CSS-only solution, I think it exists... I'm getting closer

**Comment by mccxiv** [comment]
Okay here's my plan, I'll try to do this tomorrow

1. Add a setting to turn this feature on or off (I've come to the conclusion I prefer it off, personally)
2. Add css class to overwrite the default look
3. Add this class conditionally, based on setting

Also a heads up that I probably won't use the PR, but I'm truly thankful for getting this started. 

Related: #281

**Comment by bap14** [comment]
Check out my latest changes.   I started by removing that specified line-height from chat messages.  That fixed only a part of it.  Longer messages with more emotes (see second screenshot below) still caused an overlap.  Regarding the back-to-back messages, setting a larger line-height does fix it.

So the latest commit reverts what I previously had done, and institutes a setting to enable/disable this feature.  When enabled, a generic class is added to the chat-tabs container and then as messages are added to the array they're checked for emotes and a property set on it.  This removes the looping of every message during display.  I think this now fits more inline with what you were trying to do.

I'm not 100% sure a pure-css solution is viable, with the exception of adjusting the max-height property of the emote itself to be about 18 - 20 pixels, but then the emote loses readability.

## Current Results

**Back-to-back Emote Messages**
back-to-back-emote-messages

**Emote Flood Message**
emote-flood

## Results With Commit 438068b

**Back-to-back Emote Messages**
back-to-back-emote-message-fixed

**Emote Flood Message**
emote-flood-fixed

**Comment by bap14** [comment]
Any thoughts on this?

**Comment by mccxiv** [comment]
Here's the thing: 

1. I don't like the indexOf check on every message for performance reasons
2. I'd rather not attach extra properties on messages unless truly necessary

We can do this purely with CSS, the setting will just enable or disable a class.
I'll put it on a branch tomorrow so you can see what I'm trying to do

**Comment by mccxiv** [comment]
Here's what I ended up doing, just a few lines of CSS and some code to make sure scrolling happens all the way when new images are loaded. Nevertheless I appreciate your contribution as it got me thinking about ways to approach this.

https://github.com/mccxiv/tc/tree/variable-line-height

**Comment by bap14** [comment]
Looks good.  I'll give it a test, but I never got it to look right by just removing the explicit line-height.

**Comment by mccxiv** [comment]
Cleaning up. While this wasn't merged, it helped me come up with the fix so thanks

**Pull request closed without merging**
