### PR TITLE
Modify the closing structure to allow linux to quit on close

### PR DESCRIPTION
**Pull request by scsddeputy**
To cut down on conditionals I did a switch for ya lol

### CODE REVIEW

**Comment by scsddeputy** [comment]
Partial fix for issue #331

**Comment by scsddeputy** [comment]
I'm an idiot and clicked the wrong button and closed the pr lol

**Comment by mccxiv** [comment]
This gave me an idea, perhaps it would make more sense to have app.quit be the fallback? 

So on supported systems we do the special case, while everything else quits normally

**Comment by scsddeputy** [comment]
Could do it that way if you want. Let me know and I'll modify the pr

**Comment by mccxiv** [comment]
Yeah I prefer that

**Comment by scsddeputy** [comment]
Ok I'll change it when I can

**Comment by scsddeputy** [comment]
fixed and pushed

**Pull request merged**
