### PR TITLE
Added basic osx menu items. Possibly closes #102.

### LINKED ISSUE #102: add mac menu items

### PR DESCRIPTION
**Pull request by kumpelblase2**

### CODE REVIEW

**Comment by mccxiv** [comment]
Have you tested this, good sir? I do not currently have a Mac

**Comment by kumpelblase2** [comment]
well yes I have. 
bildschirmfoto 2015-06-06 um 23 37 11
Shortcuts work by default, quit has the same behavior as normal closing.

**Comment by mccxiv** [comment]
What about that `nwjs` label?

**Comment by kumpelblase2** [comment]
That was because it was a development run, when building, it properly uses the default `tc` label.

**Pull request merged**
