### PR TITLE
Modified the structure & package.json to allow a linux build

### PR DESCRIPTION
**Pull request by scsddeputy**

### CODE REVIEW

**Comment by mccxiv** [comment]
Nice, it somewhat works. 

I launched the AppImage and didn't have the correct icon and crashed when I tried closing it.
But then I saw it added an entry to my launcher, running that one works fine.

I need to figure out how the tray/notification icon works on linux. Currently when you close the window, the app is still running in the background and there's no GUI way to quit it.

**Comment by mccxiv** [comment]
Maybe it's an Elementary OS issue. I'll try on Ubuntu after lunch

**Comment by scsddeputy** [comment]
I had issues with the tray icon as well. The current tc implementation should work correctly as it is cross os but it seems to have problems. Might have to just have I quit on close for Linux for now

**Comment by Kerrick** [comment]
For what it's worth, plenty of the apps that come with Ubuntu quit on close, so it shouldn't be that jarring to users.

**Comment by scsddeputy** [comment]
The issue could also be the low version number for electron and the builder. Could try updating the packages and testing it

**Comment by scsddeputy** [comment]
Should also note I was testing this with Linux ubuntu install

**Comment by scsddeputy** [comment]
@kerrick the problem wasn't that it was quitting on close it's that the program continues to run in the background without a tray icon to be able to actually quit the program. But I can make it so that on Linux the program will close instead of closing to tray

**Comment by mccxiv** [comment]
@scsddeputy yes please, but first I'll merge this. We can iterate

**Pull request merged**
